import {useEffect,useRef,useState} from 'react';
import {getAudioRenders,createAudioRender,getArtifact,type Artifact,type AudioRenders} from './api';
export function AudioRenderVersions({original,selected,onSelect}:{original:Artifact;selected:string;onSelect:(artifact:Artifact)=>void}){
  const pending=useRef<{key:string;id:string}|undefined>(undefined);
  const[data,setData]=useState<AudioRenders>(),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
  useEffect(()=>{let stale=false,timer:number|undefined;const refresh=async()=>{try{const next=await getAudioRenders(original.id);if(stale)return;setData(next);if(next.versions.some(v=>['queued','running','cancelling'].includes(v.state)))timer=window.setTimeout(()=>void refresh(),3000)}catch(e){if(!stale)setError(e instanceof Error?e.message:'无法读取音频版本')}};void refresh();return()=>{stale=true;if(timer)clearTimeout(timer)}},[original.id,revision]);
  async function submit(retry?:string){if(!data||busy)return;setBusy(true);setError('');try{const key=JSON.stringify([data.script_hash,data.provider_hash,retry]);if(pending.current?.key!==key)pending.current={key,id:typeof crypto.randomUUID==='function'?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`};await createAudioRender(original.id,{request_id:pending.current.id,script_hash:data.script_hash,provider_hash:data.provider_hash,retry_render_id:retry});pending.current=undefined;setRevision(v=>v+1);window.dispatchEvent(new Event('sread-quality-changed'))}catch(e){setError(e instanceof Error?e.message:'提交失败')}finally{setBusy(false)}}
  return <section className="audio-versions"><button aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{original.media_url?'音频版本与重新合成':'为已有脚本补生成音频'}</button>{open?<><p>仅合成语音并验收，不改写脚本，不调用文字模型。语音用量单独计量；提交后绑定此配置。</p>{data?<><p>服务：{data.provider.name||'未配置'} · {data.provider.base_url} · {data.provider.model}</p><p>主持人 A：{data.provider.config?.host_a_voiceprint_person_id||data.provider.config?.host_a||'服务配置'}；主持人 B：{data.provider.config?.host_b_voiceprint_person_id||data.provider.config?.host_b||'服务配置'}</p>{!data.eligible?<p>{data.reason}</p>:null}<button disabled={busy||!data.eligible||data.versions.some(v=>['queued','running','cancelling'].includes(v.state))} onClick={()=>void submit()}>按当前语音配置生成</button><button onClick={()=>setRevision(v=>v+1)}>刷新预览</button></>:<p>正在读取配置…</p>}</>:null}{data?.versions.length?<label>当前音频版本<select disabled={busy} value={selected} onChange={e=>{const id=e.target.value;if(id===original.id){onSelect(original);return}setBusy(true);void getArtifact(id).then(onSelect).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}><option value={original.id}>原始版本{original.media_url?'':'（仅脚本）'}</option>{data.versions.filter(v=>v.artifact_id).map(v=><option key={v.id} value={v.artifact_id!}>{new Date(v.created_at).toLocaleString()}</option>)}</select></label>:null}{data?.versions.filter(v=>!v.artifact_id).map(v=><p key={v.id} role="status">{({queued:'等待合成',running:'正在合成与验收',cancelling:'正在取消',failed:'音频生成失败',cancelled:'已取消'} as Record<string,string>)[v.state]||'任务已移除'}{v.error?`：${v.error}`:''}{['failed','cancelled'].includes(v.state)?<button disabled={busy||!data.eligible} onClick={()=>void submit(v.id)}>重试并复用已完成音频</button>:null}</p>)}{error?<p role="alert">{error}</p>:null}</section>
}
