import {useCallback,useDeferredValue,useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,ChevronLeft,ChevronRight,Clock3,FileText,FolderOpen,OctagonX,Plus,RotateCw,Search,Trash2,XCircle} from 'lucide-react';
import {batchDeleteNotebooks,batchPurgeJobs,cancelJob,createNotebook,deleteJob,deleteNotebook,getJob,getJobEvents,getJobsPage,getNotebookManagement,retryNotebookCleanup,type Job,type Notebook,type Page} from './api';
import {ConfirmDialog,Overlay} from './ui';

const EMPTY_PAGE={items:[],page:1,page_size:20,total:0,pages:1};
const ACTIVE_STATES=new Set(['queued','running','cancelling']);

function fmtBytes(value=0){if(value<1024)return `${value} B`;if(value<1024**2)return `${(value/1024).toFixed(1)} KB`;if(value<1024**3)return `${(value/1024**2).toFixed(1)} MB`;return `${(value/1024**3).toFixed(1)} GB`}
function fmtTime(value?:string){return value?new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—'}
function duration(value?:number){if(value===undefined)return '学习中';if(value<60)return `${value} 秒`;return `${Math.ceil(value/60)} 分钟`}
function stateIcon(state:string){if(state==='complete')return <CheckCircle2/>;if(state==='failed')return <XCircle/>;if(state==='cancelled')return <OctagonX/>;return <Clock3/>}

function Pager({page,onPage}:{page:Page<unknown>;onPage:(page:number)=>void}){return <nav className="pager" aria-label="分页"><span>{page.total} 条记录 · 第 {page.page}/{page.pages} 页</span><button aria-label="上一页" disabled={page.page<=1} onClick={()=>onPage(page.page-1)}><ChevronLeft/></button><button aria-label="下一页" disabled={page.page>=page.pages} onClick={()=>onPage(page.page+1)}><ChevronRight/></button></nav>}

type JobConfirmation={kind:'cancel'|'purge';jobs:Job[]};
export function JobsPage({onError}:{onError:(error:unknown)=>void}){
  const[data,setData]=useState<Page<Job>>(EMPTY_PAGE);const[query,setQuery]=useState('');const deferred=useDeferredValue(query);const[kind,setKind]=useState('all');const[state,setState]=useState('all');const[page,setPage]=useState(1);const[selected,setSelected]=useState<Set<string>>(new Set());const[opened,setOpened]=useState<Job>();const[events,setEvents]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[confirmation,setConfirmation]=useState<JobConfirmation>();
  const load=useCallback(async()=>{try{setData(await getJobsPage({q:deferred,kind,state,page,page_size:20,view:'summary'}))}catch(error){onError(error)}finally{setLoading(false)}},[deferred,kind,state,page,onError]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(!data.items.some(item=>ACTIVE_STATES.has(item.state)))return;const timer=window.setTimeout(()=>void load(),2000);return()=>window.clearTimeout(timer)},[data.items,load]);
  useEffect(()=>{
    if(!opened)return;
    let active=true;
    const refresh=async()=>{try{const[nextJob,nextEvents]=await Promise.all([getJob(opened.id),getJobEvents(opened.id)]);if(active){setOpened(nextJob);setEvents(nextEvents)}}catch(error){if(active)onError(error)}};
    void refresh();const timer=ACTIVE_STATES.has(opened.state)?window.setInterval(refresh,2000):undefined;
    return()=>{active=false;if(timer)window.clearInterval(timer)};
  },[opened?.id,opened?.state,onError]);
  async function confirmAction(){
    if(!confirmation)return;
    try{
      if(confirmation.kind==='cancel')await cancelJob(confirmation.jobs[0].id);
      else if(confirmation.jobs.length===1)await deleteJob(confirmation.jobs[0].id);
      else await batchPurgeJobs(confirmation.jobs.map(job=>job.id));
      setSelected(new Set());setConfirmation(undefined);if(confirmation.jobs.some(job=>job.id===opened?.id))setOpened(undefined);await load();
    }catch(error){onError(error);throw error}
  }
  const terminal=data.items.filter(item=>!ACTIVE_STATES.has(item.state));
  const confirmedCount=confirmation?.jobs.length||0;
  return <main className="management"><section className="manage-hero"><div><span>TASK ORCHESTRATOR // LOCAL QUEUE</span><h1>任务记录</h1><p>查看后台执行、真实阶段进度、历史 ETA 与资源清理状态。</p></div><div className="hero-metric"><b>{data.items.filter(item=>ACTIVE_STATES.has(item.state)).length}</b><span>本页执行中</span></div></section>
    <section className="manage-toolbar" aria-label="任务筛选"><label><Search/><span className="sr-only">搜索任务</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="搜索任务、Notebook、阶段或 ID"/></label><label className="filter-select"><span className="sr-only">任务类型</span><select value={kind} onChange={event=>{setKind(event.target.value);setPage(1)}}><option value="all">全部类型</option><option value="ingest">文档解析</option><option value="summary">摘要</option><option value="podcast">播客</option><option value="quiz">Quiz</option><option value="flashcard">Flashcard</option></select></label><label className="filter-select"><span className="sr-only">任务状态</span><select value={state} onChange={event=>{setState(event.target.value);setPage(1)}}><option value="all">全部状态</option><option value="running">执行中</option><option value="queued">排队</option><option value="complete">已完成</option><option value="failed">失败</option><option value="cancelled">已取消</option></select></label><button className="danger-action" disabled={!selected.size} onClick={()=>setConfirmation({kind:'purge',jobs:data.items.filter(item=>selected.has(item.id))})}><Trash2/> 删除 {selected.size||''}</button></section>
    <section className="manage-table" aria-busy={loading}><div className="manage-head task-grid"><input type="checkbox" aria-label="选择本页可删除任务" checked={terminal.length>0&&terminal.every(item=>selected.has(item.id))} onChange={event=>setSelected(event.target.checked?new Set(terminal.map(item=>item.id)):new Set())}/><span>任务</span><span>Notebook</span><span>阶段 / 进度</span><span>ETA</span><span>更新时间</span><span>操作</span></div>{data.items.map(job=><article className={`manage-row task-grid state-${job.state}`} key={job.id}><input type="checkbox" aria-label={`选择 ${job.display_name}`} disabled={ACTIVE_STATES.has(job.state)} checked={selected.has(job.id)} onChange={event=>setSelected(value=>{const next=new Set(value);event.target.checked?next.add(job.id):next.delete(job.id);return next})}/><button className="record-title record-open" onClick={()=>setOpened(job)} aria-label={`查看任务 ${job.display_name}`}>{stateIcon(job.state)}<span><b>{job.display_name}</b><small>{job.id.slice(0,20)} · {job.state.toUpperCase()}</small></span></button><span>{job.notebook_title||'已删除 / SYSTEM'}</span><div className="row-progress"><b>{job.stage}</b><small>{job.stage_total?`${job.stage_current}/${job.stage_total} ${job.stage_unit||''} · `:''}{Math.round(job.progress*100)}%</small><i role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(job.progress*100)}><b style={{width:`${job.progress*100}%`}}/></i></div><span>{job.state==='queued'&&job.eta.queue_position?`队列 #${job.eta.queue_position} · `:''}{job.eta.status==='learning'?`学习中 ${job.eta.sample_count}/5`:duration(job.eta.remaining_seconds)}</span><span>{fmtTime(job.updated_at)}</span><div className="row-actions">{ACTIVE_STATES.has(job.state)?<button aria-label={`终止 ${job.display_name}`} onClick={()=>setConfirmation({kind:'cancel',jobs:[job]})}><OctagonX/></button>:<button aria-label={`删除 ${job.display_name}`} onClick={()=>setConfirmation({kind:'purge',jobs:[job]})}><Trash2/></button>}</div></article>)}{!data.items.length?<div className="manage-empty">{loading?'正在读取任务…':'没有匹配的任务记录'}</div>:null}</section><Pager page={data} onPage={setPage}/>
    {opened?<Overlay className="job-detail" label={`任务详情 ${opened.display_name}`} onClose={()=>setOpened(undefined)}><button className="drawer-close" data-autofocus onClick={()=>setOpened(undefined)}>关闭 ×</button><span>TASK TRACE // {opened.id}</span><h2>{opened.display_name}</h2><div className="detail-progress"><b>{Math.round(opened.progress*100)}%</b><span>{opened.stage}</span><i role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(opened.progress*100)}><b style={{width:`${opened.progress*100}%`}}/></i></div>{opened.error?<p className="error-box"><AlertTriangle/> {opened.error}</p>:null}<dl><dt>状态</dt><dd>{opened.state}</dd><dt>Notebook</dt><dd>{opened.notebook_title||opened.notebook_id||'—'}</dd><dt>ETA</dt><dd>{opened.eta.status==='learning'?`正在学习 · ${opened.eta.sample_count}/5 个本地样本`:duration(opened.eta.remaining_seconds)}</dd><dt>创建时间</dt><dd>{fmtTime(opened.created_at)}</dd></dl><h3>阶段事件</h3><div className="event-list" aria-live="polite">{events.map(event=><div key={event.id}><i/><span><b>{event.stage}</b><small>{Math.round(event.progress*100)}% · {fmtTime(event.created_at)}</small></span></div>)}</div></Overlay>:null}
    {confirmation?<ConfirmDialog title={confirmation.kind==='cancel'?`终止“${confirmation.jobs[0].display_name}”`:`删除 ${confirmedCount} 条任务记录`} description={confirmation.kind==='cancel'?'任务会在当前安全阶段完成后停止。':'将删除任务记录及任务临时文件，正式资料和已完成产物会保留。'} confirmLabel={confirmation.kind==='cancel'?'终止任务':'删除记录'} onCancel={()=>setConfirmation(undefined)} onConfirm={confirmAction}/>:null}
  </main>;
}

type NotebookConfirmation={kind:'single'|'batch';notebooks:Notebook[]};
export function NotebooksPage({onOpen,onError,onNotify,onChanged}:{onOpen:(id:string)=>void;onError:(error:unknown)=>void;onNotify:(message:string,tone:'success'|'error')=>void;onChanged:()=>Promise<void>}){
  const[data,setData]=useState<Page<Notebook>>(EMPTY_PAGE);const[query,setQuery]=useState('');const deferred=useDeferredValue(query);const[state,setState]=useState('all');const[page,setPage]=useState(1);const[selected,setSelected]=useState<Set<string>>(new Set());const[createOpen,setCreateOpen]=useState(false);const[title,setTitle]=useState('');const[creating,setCreating]=useState(false);const[confirmation,setConfirmation]=useState<NotebookConfirmation>();const[loading,setLoading]=useState(true);const[retrying,setRetrying]=useState('');
  const load=useCallback(async()=>{try{setData(await getNotebookManagement({q:deferred,state,page,page_size:20}))}catch(error){onError(error)}finally{setLoading(false)}},[deferred,state,page,onError]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(!data.items.some(item=>item.state==='deleting'||Boolean(item.active_jobs)))return;const timer=window.setTimeout(()=>void load(),3000);return()=>window.clearTimeout(timer)},[data.items,load]);
  useEffect(()=>{const selectable=new Set(data.items.filter(item=>item.state==='active').map(item=>item.id));setSelected(current=>{const next=new Set([...current].filter(id=>selectable.has(id)));return next.size===current.size?current:next})},[data.items]);
  function closeCreate(){setCreateOpen(false);setTitle('')}
  async function create(){if(!title.trim()||creating)return;setCreating(true);try{const item=await createNotebook(title.trim());closeCreate();await load();onOpen(item.id)}catch(error){onError(error);throw error}finally{setCreating(false)}}
  async function remove(){
    if(!confirmation)return;
    try{
      if(confirmation.kind==='single'){
        const item=confirmation.notebooks[0];await deleteNotebook(item.id);setConfirmation(undefined);setSelected(current=>{const next=new Set(current);next.delete(item.id);return next});await Promise.all([load(),onChanged()]);onNotify('Notebook 删除请求已进入清理队列','success');return;
      }
      const titleById=new Map(confirmation.notebooks.map(item=>[item.id,item.title]));const result=await batchDeleteNotebooks(confirmation.notebooks.map(item=>item.id));const accepted=result.items.filter(item=>item.accepted);const failed=result.items.filter(item=>!item.accepted);const failedIds=new Set(failed.map(item=>item.id));setConfirmation(undefined);setSelected(current=>new Set([...current].filter(id=>failedIds.has(id))));await Promise.all([load(),onChanged()]);
      if(failed.length){onError(new Error(`已受理 ${accepted.length} 个，${failed.length} 个未受理：${failed.map(item=>`${titleById.get(item.id)||item.id}（${item.error||'状态已变化'}）`).join('；')}`))}
      else onNotify(`已提交 ${accepted.length} 个 Notebook 删除请求`,'success');
    }catch(error){onError(error);throw error}
  }
  async function retry(item:Notebook){setRetrying(item.id);try{await retryNotebookCleanup(item.id);await load()}catch(error){onError(error)}finally{setRetrying('')}}
  const selectable=data.items.filter(item=>item.state==='active');
  const selectedItems=data.items.filter(item=>item.state==='active'&&selected.has(item.id));
  return <main className="management"><section className="manage-hero"><div><span>KNOWLEDGE VAULT // LOCAL STORAGE</span><h1>Notebook 管理</h1><p>统一管理资料库、Studio 产物、关联任务与本地占用空间。</p></div><button className="primary hero-button" onClick={()=>setCreateOpen(true)}><Plus/> 新建 Notebook</button></section>
    <section className="manage-toolbar" aria-label="Notebook 筛选"><label><Search/><span className="sr-only">搜索 Notebook</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1);setSelected(new Set())}} placeholder="搜索名称、描述或 ID"/></label><label className="filter-select"><span className="sr-only">Notebook 状态</span><select value={state} onChange={event=>{setState(event.target.value);setPage(1);setSelected(new Set())}}><option value="all">全部状态</option><option value="active">ACTIVE</option><option value="deleting">DELETING</option><option value="cleanup_failed">CLEANUP FAILED</option></select></label><button className="danger-action" disabled={!selectedItems.length} onClick={()=>setConfirmation({kind:'batch',notebooks:selectedItems})}><Trash2/> 删除 {selectedItems.length||''}</button></section>
    <section className="manage-table" aria-busy={loading}><div className="manage-head notebook-grid"><input type="checkbox" aria-label="选择本页可删除 Notebook" checked={selectable.length>0&&selectable.every(item=>selected.has(item.id))} onChange={event=>setSelected(event.target.checked?new Set(selectable.map(item=>item.id)):new Set())}/><span>Notebook</span><span>资料</span><span>Studio</span><span>本地占用</span><span>执行中</span><span>状态</span><span>操作</span></div>{data.items.map(item=><article className="manage-row notebook-grid" key={item.id}><input type="checkbox" aria-label={`选择 ${item.title}`} disabled={item.state!=='active'} checked={selected.has(item.id)} onChange={event=>setSelected(current=>{const next=new Set(current);event.target.checked?next.add(item.id):next.delete(item.id);return next})}/><div className="record-title"><FolderOpen/><span><b>{item.title}</b><small>{item.description||item.id}</small></span></div><span>{item.source_count||0} FILES</span><span>{item.artifact_count||0} OUTPUTS</span><span>{fmtBytes(item.source_bytes)}</span><span>{item.active_jobs||0}</span><span className={`state-pill ${item.state}`}>{item.state}</span><div className="row-actions"><button aria-label={`打开 ${item.title}`} disabled={item.state!=='active'} onClick={()=>onOpen(item.id)}><FileText/></button>{item.state==='cleanup_failed'?<button aria-label={`重试清理 ${item.title}`} disabled={retrying===item.id} onClick={()=>void retry(item)}><RotateCw/></button>:null}<button aria-label={`删除 ${item.title}`} disabled={item.state!=='active'} onClick={()=>setConfirmation({kind:'single',notebooks:[item]})}><Trash2/></button></div>{item.cleanup_error?<small className="cleanup-error">{item.cleanup_error}</small>:null}</article>)}{!data.items.length?<div className="manage-empty">{loading?'正在读取 Notebook…':'没有匹配的 Notebook'}</div>:null}</section><Pager page={data} onPage={next=>{setPage(next);setSelected(new Set())}}/>
    {createOpen?<Overlay className="confirm-modal create-notebook-modal" label="新建 Notebook" onClose={closeCreate} closeOnBackdrop={false}><button className="drawer-close" onClick={closeCreate}>关闭 ×</button><span>CREATE KNOWLEDGE VAULT</span><h2>新建 Notebook</h2><label>Notebook 名称<input data-autofocus value={title} onChange={event=>setTitle(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')void create()}} placeholder="例如：产品研究 2026"/></label><div className="confirm-actions"><button onClick={closeCreate}>取消</button><button className="primary" disabled={!title.trim()||creating} onClick={()=>void create()}>{creating?'创建中…':'创建'}</button></div></Overlay>:null}
    {confirmation?<ConfirmDialog key={`${confirmation.kind}-${confirmation.notebooks.map(item=>item.id).join('-')}`} title={confirmation.kind==='single'?`删除 ${confirmation.notebooks[0].title}`:`批量删除 ${confirmation.notebooks.length} 个 Notebook`} description="系统会先终止关联任务，再清理资料、索引、对话、Studio 产物和本地文件；中断后会在下次启动继续。" confirmLabel={confirmation.kind==='single'?'删除 Notebook':`删除 ${confirmation.notebooks.length} 个 Notebook`} requireText={confirmation.kind==='single'?confirmation.notebooks[0].title:'批量删除'} items={confirmation.kind==='batch'?confirmation.notebooks.map(item=>item.title):undefined} onCancel={()=>setConfirmation(undefined)} onConfirm={remove}/>:null}
  </main>;
}
