import {useEffect,useState} from 'react';
import {qualityAction,qualityState,type QualityControl} from './api';
import {qualityLabels,qualityLevels,qualityPreference,qualityTargets,rememberQuality,type QualityLevel} from './quality_preferences';
export function useQualityPreference(kind:string){const[value,setValue]=useState(()=>qualityPreference(kind));useEffect(()=>{const refresh=()=>setValue(qualityPreference(kind));refresh();window.addEventListener('sread-quality-preference',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('sread-quality-preference',refresh);window.removeEventListener('storage',refresh)}},[kind]);return value}
export function QualitySelector({kind}:{kind:string}){const value=useQualityPreference(kind);return <label className="quality-selector">内容质量<select aria-label="内容质量" value={value} onChange={event=>rememberQuality(kind,event.target.value as QualityLevel)}>{qualityLevels.map(level=><option key={level} value={level}>{qualityLabels[level]}</option>)}</select><small>目标 {qualityTargets[value]} 分 · 自动改进最多 {value==='high'?2:value==='extreme'?3:1} 次</small></label>}
const active=(value?:QualityControl)=>Boolean(value&&['queued','generating','scoring','improving','rendering'].includes(value.phase));
const reasons:Record<string,string>={attempt_limit:'尚未达到目标，已保留最佳版本',score_unavailable:'评分暂不可用，内容已保留',budget_exhausted:'已达到用量上限，内容已保留',sources_changed:'资料已变化，已停止改进',interrupted:'任务中断，已保留完成的版本',improvement_unavailable:'本次改进未完成，已保留当前版本',kept:'已保持当前结果',cancelled:'已停止，内容已保留',generation_failed:'未能生成内容，请重新提交'};
export function QualityResult({value,targetType}:{value?:QualityControl;targetType:'artifact'|'message'}){
  const[state,setState]=useState(value),[attempts,setAttempts]=useState(1),[lower,setLower]=useState<QualityLevel>('low'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>setState(value),[value]);
  const runId=state?.run_id,working=active(state);
  useEffect(()=>{if(!runId||!working)return;let stopped=false;let timer:number|undefined;const poll=async()=>{try{const next=await qualityState(runId);if(stopped)return;setState(next);if(active(next))timer=window.setTimeout(()=>void poll(),2000)}catch{if(!stopped)timer=window.setTimeout(()=>void poll(),5000)}};timer=window.setTimeout(()=>void poll(),1000);return()=>{stopped=true;if(timer)clearTimeout(timer)}},[runId,working]);
  if(!state)return null;
  const viewed=targetType==='artifact'&&value?.version_id!==state.version_id?state.versions?.find(version=>version.version_id===value?.version_id)||value:state;
  const score=viewed?.score;
  const newer=targetType==='artifact'&&state.version_id&&value?.version_id!==state.version_id;
  const phase:Record<string,string>={queued:'等待生成',generating:'正在生成首版',scoring:'正在评分',improving:`正在改进第 ${state.attempts} 次`,rendering:'正在合成音频'};
  async function act(action:'keep'|'retry'|'lower'){
    if(!state?.version_id||busy)return;setBusy(true);setError('');try{const next=await qualityAction(state.run_id,{base_version:action==='keep'?(value?.version_id||state.version_id):state.version_id,action,attempts,quality_level:action==='lower'?lower:undefined,request_id:typeof crypto.randomUUID==='function'?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`});setState(next);window.dispatchEvent(new Event('sread-quality-changed'));window.dispatchEvent(new Event('sread-usage-changed'))}catch(error){setError(error instanceof Error?error.message:'操作失败')}finally{setBusy(false)}
  }
  const lowerChoices=qualityLevels.filter(level=>qualityTargets[level]<state.target_score);
  return <div className="quality-result"><p role="status">{score==null?'暂未评分':`自动评分 ${score}／100`} · {qualityLabels[state.quality_level].split(' · ')[0]}档目标 {state.target_score} · {working?phase[state.phase]:newer?(viewed?.met_target?'当前版本达到本档生成目标':'当前版本未达标'):state.met_target?'达到本档生成目标':reasons[state.stop_reason||'']||'已保留内容'}</p><small>AI 抽样评分，不代表事实正确率；资料覆盖与音频验收分别查看。</small>{newer?<button onClick={()=>window.dispatchEvent(new CustomEvent('sread-quality-open',{detail:state.target_id}))}>查看改进版本（当前学习或播放不受影响）</button>:null}{state.version_id&&(working||!state.met_target)?<div className="quality-actions"><button disabled={busy} onClick={()=>void act('keep')}>保持当前结果</button>{!working?<><button disabled={busy} onClick={()=>void act('retry')}>继续改进</button><details><summary>更多改进选项</summary><p>追加改进或降低要求后重试会调用模型并计入用量。</p><label>追加次数<select aria-label="追加改进次数" value={attempts} onChange={event=>setAttempts(Number(event.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} 次</option>)}</select></label>{lowerChoices.length?<><label>降低要求<select aria-label="降低质量要求" value={lower} onChange={event=>setLower(event.target.value as QualityLevel)}>{lowerChoices.map(level=><option key={level} value={level}>{qualityLabels[level]}</option>)}</select></label><button disabled={busy} onClick={()=>void act('lower')}>{state.score!=null&&!state.blocking&&state.score>=qualityTargets[lower]?'采用当前结果':'降低要求后重试'}</button></>:null}</details></>:null}</div>:null}{error?<p role="alert">{error}</p>:null}</div>
}

export function QualityEvidence({value}:{value?:QualityControl}){if(!value)return null;const labels:Record<string,string>={fidelity:'资料忠实度',requirements:'要求完成度',structure:'结构连贯',clarity:'表达清晰'};return <div className="quality-evidence"><p>自动评分是辅助判断，不是事实正确率。</p>{value.dimensions?<p>{Object.entries(value.dimensions).map(([name,score])=>`${labels[name]||name} ${score}`).join(' · ')}</p>:null}{value.coverage?<p>原文采样 {value.coverage.selected_segments}/{value.coverage.total_segments} 段{value.coverage.evidence_truncated?' · 原文因窗口限制截断':''}{value.coverage.content_truncated?' · 内容抽样评分':''}。</p>:null}{value.feedback?.length?<ul>{value.feedback.map((text,index)=><li key={index}>{text}</li>)}</ul>:null}</div>}
