import {useEffect,useState} from 'react';
import {getWeeklySettings,getWeeklyUsage,saveWeeklySettings,type WeeklyLimit,type WeeklySettings,type WeeklyOverview,type WeeklyUsage,type Provider} from './api';
import {Overlay} from './ui';

const number=(value:number)=>value.toLocaleString();
function Meter({value,metric}:{value:WeeklyUsage;metric:'tokens'|'calls'}){
  const limit=value.limit?.[metric];const known=metric==='tokens'?value.known_tokens:value.calls;const pending=metric==='tokens'?value.unconfirmed_tokens:0;
  const occupied=known+pending;const ratio=limit?occupied/limit:0;const label=metric==='tokens'?'tokens':'次文字/视觉请求';
  return <div className={`weekly-meter ${ratio>=1?'exceeded':ratio>=.8?'near':''}`}>
    <span>{metric==='tokens'?'已确认':'已调用'} {number(known)}{limit?` / ${number(limit)}`:''} {label}</span>
    {limit?<div className="weekly-track" role="progressbar" aria-label={metric==='tokens'?'本周 token 额度':'本周调用额度'} aria-valuenow={Math.min(100,Math.round(ratio*100))} aria-valuemin={0} aria-valuemax={100} aria-valuetext={`${number(known)} 已确认，${number(pending)} 待确认，额度 ${number(limit)}`}><i style={{width:`${Math.min(100,known/limit*100)}%`}}/><i className="pending" style={{width:`${Math.min(100-Math.min(100,known/limit*100),pending/limit*100)}%`}}/></div>:null}
    {pending>0?<small className="weekly-pending-note">另有 {number(pending)} tokens 执行中预留或待确认 · {value.unknown_calls} 次计量不完整</small>:null}
    {limit?<small className={ratio>=.8?'weekly-warning':undefined}>{Math.round(ratio*100)}% 已占用{pending?'（含待确认）':''} · {ratio>=1?'已达到或超过额度':ratio>=.8?'已使用至少 80%':'剩余可用估算 '+number(Math.max(0,limit-occupied))} · {value.limit?.mode==='block'?'不足时停止新请求':'仅提醒，可继续使用'}</small>:<small>未设置此项额度</small>}
  </div>
}
function LimitEditor({value,onChange,label}:{value:WeeklyLimit;onChange:(value:WeeklyLimit)=>void;label:string}){
  return <fieldset className="weekly-editor"><legend>{label}</legend>{(['tokens','calls'] as const).map(metric=><label key={metric}>{metric==='tokens'?'每周 token 额度':'每周文字/视觉调用次数'}<input type="number" min="1" max={metric==='tokens'?9e12:1e9} step="1" value={value[metric]??''} placeholder="留空关闭此项额度" onChange={event=>onChange({...value,[metric]:event.target.value===''?null:Number(event.target.value)})}/></label>)}<label>额度不足时<select value={value.mode} onChange={event=>onChange({...value,mode:event.target.value as WeeklyLimit['mode']})}><option value="warn">仅提醒，继续使用</option><option value="block">停止新请求</option></select></label></fieldset>
}
export function WeeklyBudget({providers,running,revision}:{providers:Provider[];running:boolean;revision:string}){
  const[data,setData]=useState<WeeklyOverview>();const[settings,setSettings]=useState<WeeklySettings>();const[open,setOpen]=useState(false);const[error,setError]=useState('');const[saving,setSaving]=useState(false);const[saved,setSaved]=useState(false);const[tick,setTick]=useState(0);
  useEffect(()=>{let active=true;void getWeeklySettings().then(async value=>{if(!value.initialized)value=await saveWeeklySettings({...value,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',initialize_only:true});if(active){setSettings(value);setTick(tick=>tick+1)}}).catch(error=>{if(active)setError(String(error))});return()=>{active=false}},[]);
  useEffect(()=>{const controller=new AbortController();void getWeeklyUsage(controller.signal).then(value=>{setData(value)}).catch(error=>{if(!controller.signal.aborted)setError(String(error))});return()=>controller.abort()},[revision,tick,running]);
  useEffect(()=>{const refresh=()=>{if(!document.hidden)setTick(value=>value+1)};window.addEventListener('focus',refresh);window.addEventListener('sread-usage-changed',refresh);document.addEventListener('visibilitychange',refresh);const timer=(running||data?.has_active_work)?setInterval(refresh,5000):undefined;const reset=data?setTimeout(refresh,Math.min(2147483647,Math.max(1000,new Date(data.reset_at).getTime()-Date.now()+100))):undefined;return()=>{window.removeEventListener('focus',refresh);window.removeEventListener('sread-usage-changed',refresh);document.removeEventListener('visibilitychange',refresh);clearInterval(timer);clearTimeout(reset)}},[running,data?.has_active_work,data?.reset_at]);
  let validTimezone=false;try{if(settings?.timezone){new Intl.DateTimeFormat('zh-CN',{timeZone:settings.timezone});validTimezone=true}}catch{/* Display a specific inline error. */}
  const valid=validTimezone&&settings&&[settings.global_limit,...Object.values(settings.providers)].every(limit=>(limit.tokens===null||Number.isSafeInteger(limit.tokens)&&limit.tokens>0&&limit.tokens<=9e12)&&(limit.calls===null||Number.isSafeInteger(limit.calls)&&limit.calls>0&&limit.calls<=1e9));
  async function save(){if(!settings||!valid||saving)return;setSaving(true);setSaved(false);setError('');try{setSettings(await saveWeeklySettings(settings));setSaved(true);setTick(value=>value+1)}catch(error){setError(error instanceof Error?error.message:String(error))}finally{setSaving(false)}}
  return <><button className="weekly-entry" onClick={()=>{setOpen(true);setTick(value=>value+1)}} aria-label="本周用量与额度"><b>本周用量</b>{data?<div><Meter value={data.global_usage} metric="tokens"/><Meter value={data.global_usage} metric="calls"/></div>:<span>{error?'统计暂不可用，点击重试':'正在读取…'}</span>}</button>{open?<Overlay label="用量与额度" className="weekly-dialog" onClose={()=>setOpen(false)}><button className="drawer-close" data-autofocus onClick={()=>setOpen(false)}>关闭 ×</button><h2>用量与额度</h2><p>本应用参考预算：每周 100 万 token、500 次文字/视觉模型请求；默认只提醒。不是厂商赠送额度或套餐余额。</p>{data?<><p>本周开始：{new Date(data.period_start).toLocaleString('zh-CN',{timeZone:data.timezone})} · 下次重置：{new Date(data.reset_at).toLocaleString('zh-CN',{timeZone:data.timezone})}（{data.timezone}）</p><Meter value={data.global_usage} metric="tokens"/><Meter value={data.global_usage} metric="calls"/><p>{data.notice}</p><details><summary>按 Provider 查看</summary>{data.providers.length?data.providers.map(item=><section key={item.id}><h3>{item.name}{item.kind==='ollama'?' · 本地运行':''}</h3><Meter value={item} metric="tokens"/><Meter value={item} metric="calls"/></section>):<p>本周暂无已记录调用。</p>}</details></>:null}<button onClick={()=>{setError('');setTick(value=>value+1);if(!settings)void getWeeklySettings().then(setSettings).catch(error=>setError(String(error)))}}>刷新统计</button>{settings?<><h3>额度设置</h3><label>预算时区<input value={settings.timezone} placeholder="Asia/Shanghai" onChange={event=>setSettings({...settings,timezone:event.target.value})}/></label><small>每周一零点重置；整个应用实例共用。修改额度、时区或删除资料均不会清空已有消费记录。</small><LimitEditor label="所有资料库总额度" value={settings.global_limit} onChange={value=>setSettings({...settings,global_limit:value})}/><details><summary>单独配置 Provider 额度（可选）</summary>{providers.filter(provider=>['main','vlm'].includes(provider.role)).map(provider=><section key={provider.id}><label><input type="checkbox" checked={Boolean(settings.providers[provider.id])} onChange={event=>{const limits={...settings.providers};if(event.target.checked)limits[provider.id]={tokens:null,calls:null,mode:'warn'};else delete limits[provider.id];setSettings({...settings,providers:limits})}}/>{provider.name}{provider.kind==='ollama'?' · 本地运行':''}</label>{settings.providers[provider.id]?<LimitEditor label={provider.name} value={settings.providers[provider.id]} onChange={value=>setSettings({...settings,providers:{...settings.providers,[provider.id]:value}})}/>:null}</section>)}</details><p>每次真实模型请求都计数，重试和审校会额外计数。未返回计量的请求保留预留；语音调用另计。设置仅约束本应用，不限制其他应用或官网消费。</p>{!valid?<p role="alert">{!validTimezone?'请输入有效的 IANA 时区，例如 Asia/Shanghai。':'额度请输入范围内的正整数，或留空关闭。'}</p>:null}<button disabled={!valid||saving} onClick={()=>void save()}>{saving?'保存中…':'保存额度设置'}</button>{saved?<p role="status">额度设置已保存。</p>:null}</>:null}{error?<p role="alert">{error}</p>:null}</Overlay>:null}</>
}
